"""The bytes ``tripl install`` puts on disk, and the modes it puts them at.

Golden where the exact bytes are the contract (the generated ``.env``), and
PROPERTY-based where the contract belongs to the backend rather than to this
file (the secret recipes). The second distinction is the point of this module:
asserting that ``ENCRYPTION_KEY`` is 44 characters would pin our own
implementation, whereas asserting that it decodes to exactly 32 bytes pins
Fernet's constructor - the thing that actually rejects a bad key at instance
startup (tripl-ey6j.3).
"""

from __future__ import annotations

import base64
import os
import re
import sys
from datetime import UTC, datetime
from pathlib import Path

import pytest

from tripl_cli.errors import TriplError
from tripl_cli.install import files, secrets
from tripl_cli.install.plan import APPEND, CREATE, KEPT, REPLACE, UNCHANGED, FileWrite

STAMP = datetime(2026, 8, 1, 12, 0, 0, tzinfo=UTC)


# A deterministic, obviously-fake source of "entropy". Never used outside tests;
# the production default is the stdlib CSPRNG (install/secrets.default_rng).
class StubRng:
    def __init__(self, filler: int = 0xAB) -> None:
        self.filler = filler

    def token_bytes(self, nbytes: int) -> bytes:
        return bytes([self.filler]) * nbytes

    def token_hex(self, nbytes: int) -> str:
        return f"{self.filler:02x}" * nbytes

    def token_urlsafe(self, nbytes: int) -> str:
        return "S" * nbytes


def stub_values(filler: int = 0xAB) -> dict[str, str]:
    return secrets.generate(StubRng(filler))


# --- the generated .env, byte for byte ---------------------------------------


def test_the_generated_env_is_exactly_this(install_dir: Path) -> None:
    """Golden. A change to these bytes is a review conversation, not a diff.

    Every line matters to somebody: the APP_BASE_URL comment is the one that
    prevents a CORS outage, the ENCRYPTION_KEY comment is the one that prevents
    an unrecoverable restore, and the "compose only reads what it lists" comment
    is the one that prevents an operator adding a key here and wondering why
    nothing happened.
    """
    rendered = files.render_env(
        app_base_url="https://tripl.example.com",
        image=files.DEFAULT_IMAGE,
        version="1.5.0",
        generated_at=STAMP,
        values=stub_values(),
    )
    assert rendered == (
        "# tripl instance configuration, generated by `tripl install` on "
        "2026-08-01T12:00:00Z.\n"
        "#\n"
        "# Docker Compose reads this file to INTERPOLATE compose.yaml. The containers receive\n"
        "# only the variables compose.yaml lists in its environment map, so a variable added\n"
        "# here that compose.yaml does not mention reaches nothing. Every tunable is listed at\n"
        "# https://vladenisov.github.io/tripl/run/configuration\n"
        "#\n"
        "# This file holds live secrets: mode 600, and it must stay out of version control.\n"
        "# Back up ENCRYPTION_KEY separately from the database - warehouse and alert-\n"
        "# destination credentials are encrypted with it and cannot be recovered without it.\n"
        "\n"
        "# Public origin of this instance. Drives CORS, and must be the exact origin a browser\n"
        "# reaches. The stack forces SESSION_COOKIE_SECURE=true, so this should be https.\n"
        "APP_BASE_URL=https://tripl.example.com\n"
        "\n"
        "# Released image and tag. `tripl upgrade --to X.Y.Z` moves the tag.\n"
        "TRIPL_IMAGE=ghcr.io/vladenisov/tripl\n"
        "TRIPL_VERSION=1.5.0\n"
        "\n"
        "# Generated secrets - do not edit by hand.\n"
        "# ENCRYPTION_KEY is a Fernet key: 32 random bytes, url-safe base64.\n"
        "ENCRYPTION_KEY=q6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6s=\n"
        "SECRET_KEY=SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS\n"
        "POSTGRES_PASSWORD=abababababababababababababababababababababababab\n"
        "RABBITMQ_PASSWORD=abababababababababababababababababababababababab\n"
    )


# One ${...} interpolation. Group 2 is the modifier that decides whether compose
# has a fallback: `:-`/`-` supply one, `:?`/`?` are a hard requirement, and a
# bare ${VAR} has neither - compose substitutes the empty string and the
# container gets a blank setting, which for a DSN password is the same outage as
# a missing one. So "no default" means groups 2 in (None, ':?', '?').
_INTERPOLATION = re.compile(r"\$\{([A-Za-z_][A-Za-z0-9_]*)(:?[-?])?")


def compose_mandatory_variables(body: str) -> set[str]:
    """Every ``${VAR}`` in compose.yaml that compose supplies no default for.

    Comment lines are skipped: compose.yaml documents its own `${VAR:-}` rule in
    prose, and a test that read the example would assert on a variable that does
    not exist.
    """
    mandatory: set[str] = set()
    for line in body.splitlines():
        if line.lstrip().startswith("#"):
            continue
        for name, modifier in _INTERPOLATION.findall(line):
            if modifier in ("", ":?", "?"):
                mandatory.add(name)
    return mandatory


def test_the_generated_env_defines_every_variable_compose_requires() -> None:
    """Read from compose.yaml, not from a hand-kept list.

    The list version of this test could not fail for the drift its name
    promised: a new `${NEW_THING:?}` interpolation in compose.yaml would ship a
    generated .env missing it, the stack would refuse to start, and the test
    would stay green because it only ever compared the .env against
    `secrets.REQUIRED_*` - the same module that produced it (tripl-jfm3).
    """
    rendered = files.render_env(
        app_base_url="https://tripl.example.com",
        image=files.DEFAULT_IMAGE,
        version="latest",
        generated_at=STAMP,
        values=stub_values(),
    )
    defined = files.parse_env(rendered)
    mandatory = compose_mandatory_variables(files.packaged(files.COMPOSE_NAME))

    assert mandatory, "no mandatory interpolations found - the extractor is broken"
    missing = [name for name in sorted(mandatory) if not defined.get(name)]
    assert not missing, (
        f"compose.yaml requires {missing} with no default, and the generated .env does not "
        "define them; the stack would refuse to start"
    )


def test_the_interpolation_extractor_reads_both_forms_and_ignores_comments() -> None:
    """Guards the test above. Every branch of the modifier table, on one string."""
    body = "\n".join(
        [
            "# a comment mentioning ${DOCUMENTED:-}",
            "    image: ${PLAIN}",
            "    a: ${REQUIRED_COLON:?set it}",
            "    b: ${REQUIRED_BARE?set it}",
            "    c: ${DEFAULTED_COLON:-fallback}",
            "    d: ${DEFAULTED_BARE-fallback}",
            "    e: ${EMPTY_DEFAULT:-}",
        ]
    )
    assert compose_mandatory_variables(body) == {"PLAIN", "REQUIRED_COLON", "REQUIRED_BARE"}


def test_the_generated_env_defines_every_name_the_secret_module_promises() -> None:
    """The other direction: what `install/secrets.py` says it emits, it emits."""
    rendered = files.render_env(
        app_base_url="https://tripl.example.com",
        image=files.DEFAULT_IMAGE,
        version="latest",
        generated_at=STAMP,
        values=stub_values(),
    )
    defined = files.parse_env(rendered)
    for name in (*secrets.REQUIRED_SETTINGS, *secrets.REQUIRED_SECRETS):
        assert defined.get(name), f"{name} is missing or empty in the generated .env"


# --- the renderer's own refusal ----------------------------------------------


@pytest.mark.parametrize("payload", ["one\ntwo", "one\r\ntwo", "one\x00two"])
def test_a_value_containing_a_line_break_is_refused_not_escaped(payload: str) -> None:
    """A newline here does not corrupt the file. It ADDS settings to it.

    `config.normalize_base_url` already rejects control characters in
    `--app-url`, and is the only caller that takes one from an operator today.
    This is the renderer refusing on its own account, because "the caller
    validated it" stops being true the moment a second caller appears
    (tripl-jfm3).
    """
    with pytest.raises(TriplError, match="refusing to write"):
        files.render_env(
            app_base_url=payload,
            image=files.DEFAULT_IMAGE,
            version="latest",
            generated_at=STAMP,
            values=stub_values(),
        )


def test_the_appended_block_refuses_the_same_payload(install_dir: Path) -> None:
    install_dir.mkdir(parents=True)
    (install_dir / ".env").write_text("TRIPL_IMAGE=x\n", encoding="utf-8")

    with pytest.raises(TriplError, match="refusing to write"):
        files.plan_env(
            install_dir,
            app_base_url="https://ok.example.com\nEVIL=1",
            image=files.DEFAULT_IMAGE,
            version="latest",
            generated_at=STAMP,
            values=stub_values(),
        )


# --- the secret recipes, checked against the BACKEND's contracts ---------------


def test_encryption_key_is_a_fernet_key() -> None:
    """32 raw bytes, url-safe base64.

    This IS ``Fernet.__init__``'s contract - it urlsafe_b64decodes the key and
    raises unless the result is exactly 32 bytes - restated here because this
    CLI must not depend on ``cryptography`` (tripl-mcp inherits every dependency
    of this distribution). The backend builds ``Fernet(settings.encryption_key)``
    at startup, so a key that fails this stops the instance from booting.
    """
    key = secrets.generate()["ENCRYPTION_KEY"]
    assert len(base64.urlsafe_b64decode(key)) == 32


def test_both_passwords_are_hex_only() -> None:
    """Hex is load-bearing: compose builds the DSNs by string interpolation.

    ``postgresql+asyncpg://tripl:${POSTGRES_PASSWORD}@postgres:5432/tripl``. A
    base64 password containing ``/``, ``+``, ``@`` or ``:`` corrupts that URL
    into one that fails to connect with an error naming neither the password nor
    the encoding.
    """
    values = secrets.generate()
    for name in ("POSTGRES_PASSWORD", "RABBITMQ_PASSWORD"):
        assert set(values[name]) <= set("0123456789abcdef"), name
        assert len(values[name]) == 48, name


def test_no_generated_value_is_a_dev_credential() -> None:
    """``assert_production_ready`` refuses ``tripl:tripl`` and ``guest:guest``."""
    values = secrets.generate()
    assert values["POSTGRES_PASSWORD"] != values["RABBITMQ_PASSWORD"]
    assert "tripl" not in values.values()
    assert "guest" not in values.values()


def test_two_generations_never_collide() -> None:
    first, second = secrets.generate(), secrets.generate()
    assert set(first) == set(second) == set(secrets.REQUIRED_SECRETS)
    for name in secrets.REQUIRED_SECRETS:
        assert first[name] != second[name], name


def test_the_stub_rng_is_not_the_production_one() -> None:
    """Guards the test above: an rng parameter silently ignored would fake it."""
    assert secrets.generate(StubRng(0x01)) != secrets.generate(StubRng(0x02))
    assert secrets.default_rng() is not StubRng


# --- planning and applying ----------------------------------------------------


def plan(
    directory: Path,
    *,
    values: dict[str, str] | None = None,
    force: bool = False,
    version: str = "latest",
) -> tuple[FileWrite, ...]:
    return files.plan_writes(
        directory,
        app_base_url="https://tripl.example.com",
        image=files.DEFAULT_IMAGE,
        version=version,
        generated_at=STAMP,
        values=stub_values() if values is None else values,
        force=force,
    )


def test_a_fresh_directory_plans_three_creates_and_applying_sets_the_modes(
    install_dir: Path,
) -> None:
    writes = plan(install_dir)
    assert [w.action for w in writes] == [CREATE, CREATE, CREATE]

    install_dir.mkdir(parents=True)
    files.apply(writes)

    assert (install_dir / "compose.yaml").read_text() == files.packaged("compose.yaml")
    assert (install_dir / "infra/rabbitmq/rabbitmq.conf").read_text() == files.packaged(
        "rabbitmq.conf"
    )
    if sys.platform == "win32":  # pragma: no cover - POSIX-only assertion
        return
    assert (install_dir / ".env").stat().st_mode & 0o777 == 0o600
    assert (install_dir / "compose.yaml").stat().st_mode & 0o777 == 0o644
    assert (install_dir / "infra/rabbitmq/rabbitmq.conf").stat().st_mode & 0o777 == 0o644


def test_a_complete_env_is_never_opened_for_writing(install_dir: Path) -> None:
    """The load-bearing rule. Re-running install must not touch live secrets."""
    install_dir.mkdir(parents=True)
    files.apply(plan(install_dir))
    env = install_dir / ".env"
    before = env.read_bytes()
    stat_before = env.stat()

    again = plan(install_dir, values=stub_values(0x11))
    assert [w.action for w in again] == [UNCHANGED, UNCHANGED, KEPT]
    files.apply(again)

    assert env.read_bytes() == before
    assert env.stat().st_mtime_ns == stat_before.st_mtime_ns


def test_an_incomplete_env_is_appended_to_and_every_existing_line_survives(
    install_dir: Path,
) -> None:
    install_dir.mkdir(parents=True)
    env = install_dir / ".env"
    # No trailing newline on purpose: appending must complete that last line
    # rather than run our first key onto the end of it.
    original = (
        "# my own header\n"
        "APP_BASE_URL=https://mine.example.com\n"
        "\n"
        "ENCRYPTION_KEY=already-set\n"
        "SECRET_KEY=already-set\n"
        "POSTGRES_PASSWORD=already-set\n"
        "TRIPL_IMAGE=ghcr.io/vladenisov/tripl\n"
        "TRIPL_VERSION=1.4.0"
    )
    env.write_text(original, encoding="utf-8")
    os.chmod(env, 0o600)

    write = plan(install_dir)[2]
    assert write.action == APPEND
    assert write.keys == ("RABBITMQ_PASSWORD",)
    files.apply([write])

    updated = env.read_text(encoding="utf-8")
    assert updated.startswith(original)
    assert files.parse_env(updated)["TRIPL_VERSION"] == "1.4.0"
    assert files.parse_env(updated)["ENCRYPTION_KEY"] == "already-set"
    assert files.parse_env(updated)["RABBITMQ_PASSWORD"] == stub_values()["RABBITMQ_PASSWORD"]
    if sys.platform != "win32":
        assert env.stat().st_mode & 0o777 == 0o600


def test_a_differing_compose_is_kept_unless_forced(install_dir: Path) -> None:
    install_dir.mkdir(parents=True)
    compose = install_dir / "compose.yaml"
    compose.write_text("services: {}\n", encoding="utf-8")

    kept = plan(install_dir)[0]
    assert kept.action == KEPT
    assert "differs" in kept.note
    files.apply([kept])
    assert compose.read_text() == "services: {}\n"

    forced = plan(install_dir, force=True)[0]
    assert forced.action == REPLACE
    files.apply([forced])
    assert compose.read_text() == files.packaged("compose.yaml")


def test_force_keeps_a_timestamped_copy_of_what_it_replaced(install_dir: Path) -> None:
    """The same promise `upgrade` makes about `.env`, on the two files --force reaches.

    A compose.yaml that differs is the operator's: a TLS tweak, a changed port,
    a second network. Replacing it with no copy and no diff was one command
    holding two standards (tripl-jfm3).
    """
    install_dir.mkdir(parents=True)
    compose = install_dir / "compose.yaml"
    rabbit = install_dir / files.RABBITMQ_RELATIVE
    rabbit.parent.mkdir(parents=True)
    compose.write_text("services: {}  # mine\n", encoding="utf-8")
    rabbit.write_text("consumer_timeout = 1\n", encoding="utf-8")

    writes = plan(install_dir, force=True)
    assert [w.action for w in writes[:2]] == [REPLACE, REPLACE]
    files.apply(writes[:2])

    for path, original in ((compose, "services: {}  # mine\n"), (rabbit, "consumer_timeout = 1\n")):
        backup = files.backup_path(path, STAMP)
        assert backup.name == f"{path.name}.bak.20260801T120000Z"
        assert backup.read_text() == original, f"{path.name} was replaced with no copy kept"
    # ...and the note names it, so the operator can diff without being told where.
    assert "compose.yaml.bak.20260801T120000Z" in writes[0].note
    assert compose.read_text() == files.packaged("compose.yaml")


def test_a_second_force_in_the_same_second_refuses_rather_than_clobbers(
    install_dir: Path,
) -> None:
    """Identical rule to the .env backup: the copy is the only remaining original."""
    install_dir.mkdir(parents=True)
    compose = install_dir / "compose.yaml"
    compose.write_text("services: {}  # mine\n", encoding="utf-8")
    files.apply(plan(install_dir, force=True)[:1])
    first = files.backup_path(compose, STAMP).read_bytes()

    compose.write_text("services: {}  # mine, again\n", encoding="utf-8")
    with pytest.raises(TriplError, match="could not write"):
        files.apply(plan(install_dir, force=True)[:1])

    assert files.backup_path(compose, STAMP).read_bytes() == first
    # The replace never happened, so the operator's second edit is still there.
    assert compose.read_text() == "services: {}  # mine, again\n"


# --- what will actually be true ----------------------------------------------


def settings(directory: Path, *, url: str, version: str) -> dict[str, tuple[str, str, bool]]:
    return {
        outcome.name: (outcome.requested, outcome.effective, outcome.applied)
        for outcome in files.plan_settings(
            directory, app_base_url=url, image=files.DEFAULT_IMAGE, version=version
        )
    }


def test_a_fresh_directory_applies_every_requested_setting(install_dir: Path) -> None:
    resolved = settings(install_dir, url="https://new.example.com", version="1.5.0")
    assert resolved["APP_BASE_URL"] == ("https://new.example.com", "https://new.example.com", True)
    assert resolved["TRIPL_VERSION"] == ("1.5.0", "1.5.0", True)


def test_an_existing_env_wins_and_says_it_did(install_dir: Path) -> None:
    """`.env` is never overwritten, so it - not the flags - decides. Report that."""
    install_dir.mkdir(parents=True)
    (install_dir / ".env").write_text(
        "APP_BASE_URL=https://old.example.com\nTRIPL_VERSION=1.4.0\n", encoding="utf-8"
    )

    resolved = settings(install_dir, url="https://new.example.com", version="1.5.0")
    assert resolved["APP_BASE_URL"] == ("https://new.example.com", "https://old.example.com", False)
    assert resolved["TRIPL_VERSION"] == ("1.5.0", "1.4.0", False)
    # TRIPL_IMAGE is absent from that file, so the default does apply.
    assert resolved["TRIPL_IMAGE"][2] is True


def test_an_empty_value_counts_as_absent(install_dir: Path) -> None:
    """`APP_BASE_URL=` satisfies neither compose's `${VAR:?}` nor `missing_keys`."""
    install_dir.mkdir(parents=True)
    (install_dir / ".env").write_text("APP_BASE_URL=\n", encoding="utf-8")

    resolved = settings(install_dir, url="https://new.example.com", version="1.5.0")
    assert resolved["APP_BASE_URL"][1] == "https://new.example.com"


# --- the version pin ----------------------------------------------------------


def test_rewriting_the_pin_changes_exactly_one_line(install_dir: Path) -> None:
    """Comments, blank lines, key order and the trailing newline all survive.

    An upgrade that reformatted the operator's .env would make every subsequent
    `git diff` of their configuration repository unreadable, and would be the
    kind of surprise that stops people running `tripl upgrade` at all.
    """
    install_dir.mkdir(parents=True)
    env = install_dir / ".env"
    original = (
        "# hand-written\n"
        "APP_BASE_URL=https://mine.example.com\n"
        "\n"
        "TRIPL_VERSION=1.4.0\n"
        "# a trailing comment\n"
        "SECRET_KEY=abc\n"
    )
    env.write_text(original, encoding="utf-8")
    os.chmod(env, 0o600)

    backup = files.rewrite_version(env, "1.5.0", stamp=STAMP)

    assert env.read_text() == original.replace("TRIPL_VERSION=1.4.0", "TRIPL_VERSION=1.5.0")
    assert backup.name == ".env.bak.20260801T120000Z"
    assert backup.read_text() == original
    if sys.platform != "win32":
        assert backup.stat().st_mode & 0o777 == 0o600
        assert env.stat().st_mode & 0o777 == 0o600


def test_rewriting_appends_the_pin_when_the_file_has_none(install_dir: Path) -> None:
    install_dir.mkdir(parents=True)
    env = install_dir / ".env"
    env.write_text("APP_BASE_URL=https://mine.example.com", encoding="utf-8")

    files.rewrite_version(env, "1.5.0", stamp=STAMP)

    assert env.read_text() == "APP_BASE_URL=https://mine.example.com\nTRIPL_VERSION=1.5.0\n"


def test_an_unwritable_directory_is_a_message_not_a_traceback(install_dir: Path) -> None:
    """An operator whose /srv is read-only must read "not writable", not a stack."""
    if sys.platform == "win32" or os.geteuid() == 0:  # pragma: no cover - root ignores 0o500
        pytest.skip("file modes do not restrain this user")
    install_dir.mkdir(parents=True)
    os.chmod(install_dir, 0o500)
    try:
        with pytest.raises(TriplError, match="could not write"):
            files.apply(plan(install_dir))
    finally:
        os.chmod(install_dir, 0o700)


def test_a_second_backup_in_the_same_second_refuses_rather_than_clobbers(
    install_dir: Path,
) -> None:
    """The previous pin is the only thing standing between an operator and a guess."""
    install_dir.mkdir(parents=True)
    env = install_dir / ".env"
    env.write_text("TRIPL_VERSION=1.4.0\n", encoding="utf-8")
    files.rewrite_version(env, "1.5.0", stamp=STAMP)
    first = (install_dir / files.backup_name(STAMP)).read_bytes()

    with pytest.raises(TriplError, match="still holds the current pin"):
        files.rewrite_version(env, "1.6.0", stamp=STAMP)

    assert (install_dir / files.backup_name(STAMP)).read_bytes() == first
    assert files.current_version(env.read_text()) == "1.5.0"


def test_current_version_reads_the_pin_and_tolerates_junk() -> None:
    assert files.current_version("TRIPL_VERSION=1.4.0\n") == "1.4.0"
    assert files.current_version("# TRIPL_VERSION=1.4.0\n") is None
    assert files.current_version("TRIPL_VERSION=\n") is None
    assert files.current_version("") is None


# --- refusals -----------------------------------------------------------------


@pytest.mark.parametrize("marker", [".git", "backend/src/tripl"])
def test_a_source_checkout_is_recognised(install_dir: Path, marker: str) -> None:
    (install_dir / marker).mkdir(parents=True)
    assert files.looks_like_source_checkout(install_dir) is not None


def test_an_ordinary_directory_is_not_a_source_checkout(install_dir: Path) -> None:
    install_dir.mkdir(parents=True)
    (install_dir / "compose.yaml").write_text("x", encoding="utf-8")
    assert files.looks_like_source_checkout(install_dir) is None


@pytest.mark.skipif(sys.platform == "win32", reason="st_mode carries no such meaning")
def test_world_readable_mode_reports_only_loose_modes(install_dir: Path) -> None:
    install_dir.mkdir(parents=True)
    path = install_dir / ".env"
    path.write_text("SECRET_KEY=x\n", encoding="utf-8")
    os.chmod(path, 0o644)
    assert files.world_readable_mode(path) == 0o644
    os.chmod(path, 0o600)
    assert files.world_readable_mode(path) is None
