"""initial schema

Revision ID: af42585c6630
Revises:
Create Date: 2026-05-20 20:51:43.619421
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "af42585c6630"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_sources",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("db_type", sa.String(length=20), nullable=False),
        sa.Column("host", sa.String(length=500), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("database_name", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("password_encrypted", sa.Text(), nullable=False),
        sa.Column("extra_params", sa.JSON(), nullable=True),
        sa.Column("last_test_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_test_status", sa.String(length=16), nullable=True),
        sa.Column("last_test_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_data_source_name"),
    )
    op.create_table(
        "projects",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_projects_slug"), "projects", ["slug"], unique=True)
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("role", sa.String(length=20), server_default="editor", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "alert_destinations",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("webhook_url_encrypted", sa.Text(), nullable=True),
        sa.Column("bot_token_encrypted", sa.Text(), nullable=True),
        sa.Column("chat_id", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_alert_destination_project", "alert_destinations", ["project_id"], unique=False
    )
    op.create_table(
        "audit_log",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("user_email", sa.String(length=320), server_default="", nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("project_slug", sa.String(length=255), server_default="", nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target_type", sa.String(length=32), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=True),
        sa.Column("target_name", sa.String(length=255), server_default="", nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "event_types",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("color", sa.String(length=7), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "name", name="uq_event_type_project_name"),
    )
    op.create_table(
        "meta_field_definitions",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("field_type", sa.String(length=20), nullable=False),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("enum_options", sa.JSON(), nullable=True),
        sa.Column("default_value", sa.Text(), nullable=True),
        sa.Column("link_template", sa.Text(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("sensitivity", sa.String(length=20), server_default="none", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "name", name="uq_meta_field_def_project_name"),
    )
    op.create_table(
        "plan_revisions",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("summary", sa.Text(), server_default="", nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_plan_revisions_project_created",
        "plan_revisions",
        ["project_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "project_anomaly_settings",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("anomaly_detection_enabled", sa.Boolean(), nullable=False),
        sa.Column("detect_project_total", sa.Boolean(), nullable=False),
        sa.Column("detect_event_types", sa.Boolean(), nullable=False),
        sa.Column("detect_events", sa.Boolean(), nullable=False),
        sa.Column("baseline_window_buckets", sa.Integer(), nullable=False),
        sa.Column("min_history_buckets", sa.Integer(), nullable=False),
        sa.Column("sigma_threshold", sa.Float(), nullable=False),
        sa.Column("min_expected_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", name="uq_project_anomaly_settings_project"),
    )
    op.create_table(
        "user_sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("session_token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_sessions_expires_at"), "user_sessions", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_user_sessions_session_token_hash"),
        "user_sessions",
        ["session_token_hash"],
        unique=True,
    )
    op.create_index(op.f("ix_user_sessions_user_id"), "user_sessions", ["user_id"], unique=False)
    op.create_table(
        "variables",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("source_name", sa.String(length=100), nullable=True),
        sa.Column("variable_type", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "name", name="uq_variable_project_name"),
        sa.UniqueConstraint("project_id", "source_name", name="uq_variable_project_source_name"),
    )
    op.create_table(
        "alert_rules",
        sa.Column("destination_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("include_project_total", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("include_event_types", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("include_events", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("include_schema_drifts", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("notify_on_spike", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("notify_on_drop", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("min_percent_delta", sa.Float(), server_default="0", nullable=False),
        sa.Column("min_absolute_delta", sa.Float(), server_default="0", nullable=False),
        sa.Column("min_expected_count", sa.Float(), server_default="0", nullable=False),
        sa.Column("cooldown_minutes", sa.Integer(), server_default="1440", nullable=False),
        sa.Column("message_template", sa.Text(), nullable=True),
        sa.Column("items_template", sa.Text(), nullable=True),
        sa.Column("message_format", sa.String(length=64), server_default="plain", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["destination_id"], ["alert_destinations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_alert_rule_destination", "alert_rules", ["destination_id"], unique=False)
    op.create_table(
        "events",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("event_type_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("implemented", sa.Boolean(), nullable=False),
        sa.Column("reviewed", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("archived", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["event_type_id"], ["event_types.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_event_event_type", "events", ["event_type_id"], unique=False)
    op.create_index("ix_event_project_order", "events", ["project_id", "order"], unique=False)
    op.create_index("ix_events_last_seen_at", "events", ["last_seen_at"], unique=False)
    op.create_table(
        "field_definitions",
        sa.Column("event_type_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("field_type", sa.String(length=20), nullable=False),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("enum_options", sa.JSON(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("sensitivity", sa.String(length=20), server_default="none", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["event_type_id"], ["event_types.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_type_id", "name", name="uq_field_def_event_type_name"),
    )
    op.create_table(
        "scan_configs",
        sa.Column("data_source_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("event_type_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("base_query", sa.Text(), nullable=False),
        sa.Column("event_type_column", sa.String(length=255), nullable=True),
        sa.Column("time_column", sa.String(length=255), nullable=True),
        sa.Column("event_name_format", sa.String(length=500), nullable=True),
        sa.Column("json_value_paths", sa.JSON(), server_default="[]", nullable=False),
        sa.Column("metric_breakdown_columns", sa.JSON(), server_default="[]", nullable=False),
        sa.Column("metric_breakdown_values_limit", sa.Integer(), nullable=True),
        sa.Column("cardinality_threshold", sa.Integer(), nullable=False),
        sa.Column("interval", sa.String(length=10), nullable=True),
        sa.Column("anomaly_detection_enabled", sa.Boolean(), nullable=False),
        sa.Column("detect_project_total", sa.Boolean(), nullable=False),
        sa.Column("detect_event_types", sa.Boolean(), nullable=False),
        sa.Column("detect_events", sa.Boolean(), nullable=False),
        sa.Column("baseline_window_buckets", sa.Integer(), nullable=False),
        sa.Column("min_history_buckets", sa.Integer(), nullable=False),
        sa.Column("sigma_threshold", sa.Float(), nullable=False),
        sa.Column("min_expected_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["data_source_id"], ["data_sources.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["event_type_id"], ["event_types.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("data_source_id", "name", name="uq_scan_config_ds_name"),
    )
    op.create_index("ix_scan_config_project", "scan_configs", ["project_id"], unique=False)
    op.create_table(
        "alert_rule_filters",
        sa.Column("rule_id", sa.Uuid(), nullable=False),
        sa.Column("field", sa.String(length=32), nullable=False),
        sa.Column("operator", sa.String(length=16), nullable=False),
        sa.Column("values", sa.JSON(), nullable=False),
        sa.Column("position", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["rule_id"], ["alert_rules.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_alert_rule_filter_rule", "alert_rule_filters", ["rule_id"], unique=False)
    op.create_table(
        "event_field_values",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("field_definition_id", sa.Uuid(), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["field_definition_id"], ["field_definitions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "event_id", "field_definition_id", name="uq_event_field_value_event_field"
        ),
    )
    op.create_table(
        "event_meta_values",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("meta_field_definition_id", sa.Uuid(), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["meta_field_definition_id"], ["meta_field_definitions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "event_id", "meta_field_definition_id", name="uq_event_meta_value_event_meta"
        ),
    )
    op.create_table(
        "event_metric_breakdowns",
        sa.Column("scan_config_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=True),
        sa.Column("event_type_id", sa.Uuid(), nullable=True),
        sa.Column("bucket", sa.DateTime(timezone=True), nullable=False),
        sa.Column("breakdown_column", sa.String(length=255), nullable=False),
        sa.Column("breakdown_value", sa.String(length=500), nullable=False),
        sa.Column("is_other", sa.Boolean(), nullable=False),
        sa.Column("count", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["event_type_id"], ["event_types.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["scan_config_id"], ["scan_configs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "scan_config_id",
            "event_id",
            "bucket",
            "breakdown_column",
            "breakdown_value",
            "is_other",
            name="uq_event_metric_breakdown_config_event_bucket_value",
        ),
        sa.UniqueConstraint(
            "scan_config_id",
            "event_type_id",
            "bucket",
            "breakdown_column",
            "breakdown_value",
            "is_other",
            name="uq_event_metric_breakdown_config_type_bucket_value",
        ),
    )
    op.create_index(
        "ix_event_metric_breakdown_config_column_bucket",
        "event_metric_breakdowns",
        ["scan_config_id", "breakdown_column", "bucket"],
        unique=False,
    )
    op.create_index(
        "ix_event_metric_breakdown_event_bucket",
        "event_metric_breakdowns",
        ["event_id", "breakdown_column", "bucket"],
        unique=False,
    )
    op.create_index(
        "ix_event_metric_breakdown_type_bucket",
        "event_metric_breakdowns",
        ["event_type_id", "breakdown_column", "bucket"],
        unique=False,
    )
    op.create_table(
        "event_metrics",
        sa.Column("scan_config_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=True),
        sa.Column("event_type_id", sa.Uuid(), nullable=True),
        sa.Column("bucket", sa.DateTime(timezone=True), nullable=False),
        sa.Column("count", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["event_type_id"], ["event_types.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["scan_config_id"], ["scan_configs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "scan_config_id", "event_id", "bucket", name="uq_event_metric_config_event_bucket"
        ),
        sa.UniqueConstraint(
            "scan_config_id", "event_type_id", "bucket", name="uq_event_metric_config_type_bucket"
        ),
    )
    op.create_index(
        "ix_event_metric_event_bucket", "event_metrics", ["event_id", "bucket"], unique=False
    )
    op.create_index(
        "ix_event_metric_type_bucket", "event_metrics", ["event_type_id", "bucket"], unique=False
    )
    op.create_table(
        "event_photos",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("uploaded_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("original_filename", sa.String(length=500), nullable=False),
        sa.Column("content_type", sa.String(length=120), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("storage_backend", sa.String(length=20), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["uploaded_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_event_photo_event_order", "event_photos", ["event_id", "sort_order"], unique=False
    )
    op.create_table(
        "event_tags",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "name", name="uq_event_tag"),
    )
    op.create_index("ix_event_tag_name", "event_tags", ["name"], unique=False)
    op.create_table(
        "event_type_relations",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("source_event_type_id", sa.Uuid(), nullable=False),
        sa.Column("target_event_type_id", sa.Uuid(), nullable=False),
        sa.Column("source_field_id", sa.Uuid(), nullable=False),
        sa.Column("target_field_id", sa.Uuid(), nullable=False),
        sa.Column("relation_type", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_event_type_id"], ["event_types.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_field_id"], ["field_definitions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_event_type_id"], ["event_types.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_field_id"], ["field_definitions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "metric_anomalies",
        sa.Column("scan_config_id", sa.Uuid(), nullable=False),
        sa.Column("scope_type", sa.String(length=32), nullable=False),
        sa.Column("scope_ref", sa.String(length=64), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=True),
        sa.Column("event_type_id", sa.Uuid(), nullable=True),
        sa.Column("bucket", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actual_count", sa.BigInteger(), nullable=False),
        sa.Column("expected_count", sa.Float(), nullable=False),
        sa.Column("stddev", sa.Float(), nullable=False),
        sa.Column("z_score", sa.Float(), nullable=False),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["event_type_id"], ["event_types.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["scan_config_id"], ["scan_configs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "scan_config_id",
            "scope_type",
            "scope_ref",
            "bucket",
            name="uq_metric_anomaly_scope_bucket",
        ),
    )
    op.create_index(
        "ix_metric_anomaly_event_bucket", "metric_anomalies", ["event_id", "bucket"], unique=False
    )
    op.create_index(
        "ix_metric_anomaly_scope_bucket",
        "metric_anomalies",
        ["scan_config_id", "scope_type", "scope_ref", "bucket"],
        unique=False,
    )
    op.create_index(
        "ix_metric_anomaly_type_bucket",
        "metric_anomalies",
        ["event_type_id", "bucket"],
        unique=False,
    )
    op.create_table(
        "metric_breakdown_anomalies",
        sa.Column("scan_config_id", sa.Uuid(), nullable=False),
        sa.Column("scope_type", sa.String(length=32), nullable=False),
        sa.Column("scope_ref", sa.String(length=64), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=True),
        sa.Column("event_type_id", sa.Uuid(), nullable=True),
        sa.Column("bucket", sa.DateTime(timezone=True), nullable=False),
        sa.Column("breakdown_column", sa.String(length=255), nullable=False),
        sa.Column("breakdown_value", sa.String(length=500), nullable=False),
        sa.Column("is_other", sa.Boolean(), nullable=False),
        sa.Column("actual_count", sa.BigInteger(), nullable=False),
        sa.Column("expected_count", sa.Float(), nullable=False),
        sa.Column("stddev", sa.Float(), nullable=False),
        sa.Column("z_score", sa.Float(), nullable=False),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["event_type_id"], ["event_types.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["scan_config_id"], ["scan_configs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "scan_config_id",
            "scope_type",
            "scope_ref",
            "breakdown_column",
            "breakdown_value",
            "is_other",
            "bucket",
            name="uq_metric_breakdown_anomaly_scope_bucket_value",
        ),
    )
    op.create_index(
        "ix_metric_breakdown_anomaly_event_bucket",
        "metric_breakdown_anomalies",
        ["event_id", "breakdown_column", "bucket"],
        unique=False,
    )
    op.create_index(
        "ix_metric_breakdown_anomaly_scope_bucket",
        "metric_breakdown_anomalies",
        [
            "scan_config_id",
            "scope_type",
            "scope_ref",
            "breakdown_column",
            "breakdown_value",
            "is_other",
            "bucket",
        ],
        unique=False,
    )
    op.create_index(
        "ix_metric_breakdown_anomaly_type_bucket",
        "metric_breakdown_anomalies",
        ["event_type_id", "breakdown_column", "bucket"],
        unique=False,
    )
    op.create_table(
        "scan_jobs",
        sa.Column("scan_config_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("result_summary", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["scan_config_id"], ["scan_configs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_scan_job_config", "scan_jobs", ["scan_config_id"], unique=False)
    op.create_table(
        "schema_drifts",
        sa.Column("event_type_id", sa.Uuid(), nullable=False),
        sa.Column("scan_config_id", sa.Uuid(), nullable=True),
        sa.Column("field_name", sa.String(length=255), nullable=False),
        sa.Column("drift_type", sa.String(length=32), nullable=False),
        sa.Column("observed_type", sa.String(length=128), nullable=True),
        sa.Column("declared_type", sa.String(length=64), nullable=True),
        sa.Column("sample_value", sa.Text(), nullable=True),
        sa.Column(
            "detected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["event_type_id"], ["event_types.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scan_config_id"], ["scan_configs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "event_type_id",
            "field_name",
            "drift_type",
            name="uq_schema_drift_event_type_field_kind",
        ),
    )
    op.create_index(
        "ix_schema_drift_event_type_detected",
        "schema_drifts",
        ["event_type_id", "detected_at"],
        unique=False,
    )
    op.create_table(
        "alert_deliveries",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("scan_config_id", sa.Uuid(), nullable=False),
        sa.Column("scan_job_id", sa.Uuid(), nullable=True),
        sa.Column("destination_id", sa.Uuid(), nullable=False),
        sa.Column("rule_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="pending", nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("matched_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("payload_snapshot", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["destination_id"], ["alert_destinations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["rule_id"], ["alert_rules.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scan_config_id"], ["scan_configs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scan_job_id"], ["scan_jobs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_alert_delivery_destination_created",
        "alert_deliveries",
        ["destination_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_alert_delivery_project_created",
        "alert_deliveries",
        ["project_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_alert_delivery_rule_created",
        "alert_deliveries",
        ["rule_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_alert_delivery_scan_created",
        "alert_deliveries",
        ["scan_config_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "alert_delivery_items",
        sa.Column("delivery_id", sa.Uuid(), nullable=False),
        sa.Column("scope_type", sa.String(length=32), nullable=False),
        sa.Column("scope_ref", sa.String(length=64), nullable=False),
        sa.Column("scope_name", sa.String(length=255), nullable=False),
        sa.Column("event_type_id", sa.Uuid(), nullable=True),
        sa.Column("event_id", sa.Uuid(), nullable=True),
        sa.Column("bucket", sa.DateTime(timezone=True), nullable=False),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("actual_count", sa.Integer(), nullable=False),
        sa.Column("expected_count", sa.Integer(), nullable=False),
        sa.Column("absolute_delta", sa.Integer(), nullable=False),
        sa.Column("percent_delta", sa.Float(), nullable=False),
        sa.Column("details_path", sa.String(length=500), nullable=True),
        sa.Column("monitoring_path", sa.String(length=500), nullable=True),
        sa.Column("drift_field", sa.String(length=255), nullable=True),
        sa.Column("drift_type", sa.String(length=32), nullable=True),
        sa.Column("sample_value", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["delivery_id"], ["alert_deliveries.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["event_type_id"], ["event_types.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_alert_delivery_item_delivery", "alert_delivery_items", ["delivery_id"], unique=False
    )
    op.create_table(
        "alert_rule_states",
        sa.Column("rule_id", sa.Uuid(), nullable=False),
        sa.Column("scan_config_id", sa.Uuid(), nullable=False),
        sa.Column("scope_type", sa.String(length=32), nullable=False),
        sa.Column("scope_ref", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_anomaly_bucket", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_notified_delivery_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["last_notified_delivery_id"], ["alert_deliveries.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["rule_id"], ["alert_rules.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scan_config_id"], ["scan_configs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "rule_id", "scan_config_id", "scope_type", "scope_ref", name="uq_alert_rule_state_scope"
        ),
    )
    op.create_index("ix_alert_rule_state_rule", "alert_rule_states", ["rule_id"], unique=False)
    op.create_index(
        "ix_alert_rule_state_scan", "alert_rule_states", ["scan_config_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_alert_rule_state_scan", table_name="alert_rule_states")
    op.drop_index("ix_alert_rule_state_rule", table_name="alert_rule_states")
    op.drop_table("alert_rule_states")
    op.drop_index("ix_alert_delivery_item_delivery", table_name="alert_delivery_items")
    op.drop_table("alert_delivery_items")
    op.drop_index("ix_alert_delivery_scan_created", table_name="alert_deliveries")
    op.drop_index("ix_alert_delivery_rule_created", table_name="alert_deliveries")
    op.drop_index("ix_alert_delivery_project_created", table_name="alert_deliveries")
    op.drop_index("ix_alert_delivery_destination_created", table_name="alert_deliveries")
    op.drop_table("alert_deliveries")
    op.drop_index("ix_schema_drift_event_type_detected", table_name="schema_drifts")
    op.drop_table("schema_drifts")
    op.drop_index("ix_scan_job_config", table_name="scan_jobs")
    op.drop_table("scan_jobs")
    op.drop_index(
        "ix_metric_breakdown_anomaly_type_bucket", table_name="metric_breakdown_anomalies"
    )
    op.drop_index(
        "ix_metric_breakdown_anomaly_scope_bucket", table_name="metric_breakdown_anomalies"
    )
    op.drop_index(
        "ix_metric_breakdown_anomaly_event_bucket", table_name="metric_breakdown_anomalies"
    )
    op.drop_table("metric_breakdown_anomalies")
    op.drop_index("ix_metric_anomaly_type_bucket", table_name="metric_anomalies")
    op.drop_index("ix_metric_anomaly_scope_bucket", table_name="metric_anomalies")
    op.drop_index("ix_metric_anomaly_event_bucket", table_name="metric_anomalies")
    op.drop_table("metric_anomalies")
    op.drop_table("event_type_relations")
    op.drop_index("ix_event_tag_name", table_name="event_tags")
    op.drop_table("event_tags")
    op.drop_index("ix_event_photo_event_order", table_name="event_photos")
    op.drop_table("event_photos")
    op.drop_index("ix_event_metric_type_bucket", table_name="event_metrics")
    op.drop_index("ix_event_metric_event_bucket", table_name="event_metrics")
    op.drop_table("event_metrics")
    op.drop_index("ix_event_metric_breakdown_type_bucket", table_name="event_metric_breakdowns")
    op.drop_index("ix_event_metric_breakdown_event_bucket", table_name="event_metric_breakdowns")
    op.drop_index(
        "ix_event_metric_breakdown_config_column_bucket", table_name="event_metric_breakdowns"
    )
    op.drop_table("event_metric_breakdowns")
    op.drop_table("event_meta_values")
    op.drop_table("event_field_values")
    op.drop_index("ix_alert_rule_filter_rule", table_name="alert_rule_filters")
    op.drop_table("alert_rule_filters")
    op.drop_index("ix_scan_config_project", table_name="scan_configs")
    op.drop_table("scan_configs")
    op.drop_table("field_definitions")
    op.drop_index("ix_events_last_seen_at", table_name="events")
    op.drop_index("ix_event_project_order", table_name="events")
    op.drop_index("ix_event_event_type", table_name="events")
    op.drop_table("events")
    op.drop_index("ix_alert_rule_destination", table_name="alert_rules")
    op.drop_table("alert_rules")
    op.drop_table("variables")
    op.drop_index(op.f("ix_user_sessions_user_id"), table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_session_token_hash"), table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_expires_at"), table_name="user_sessions")
    op.drop_table("user_sessions")
    op.drop_table("project_anomaly_settings")
    op.drop_index("ix_plan_revisions_project_created", table_name="plan_revisions")
    op.drop_table("plan_revisions")
    op.drop_table("meta_field_definitions")
    op.drop_table("event_types")
    op.drop_table("audit_log")
    op.drop_index("ix_alert_destination_project", table_name="alert_destinations")
    op.drop_table("alert_destinations")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_projects_slug"), table_name="projects")
    op.drop_table("projects")
    op.drop_table("data_sources")
    # ### end Alembic commands ###
