import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Sidebar is generated from the docs/ folder structure; ordering and labels
// come from each section's _category_.json and per-doc sidebar_position.
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
